Avoid naming collisions with brooklyn-hyperledger
cloudsoft/brooklyn-hyperledger-kubernetes pull request #5
Opened 2017-02-28 16:43 UTC by mikezaccardo

2017-02-28 17:24 UTC, grkvlt requested changes
Keep changed catalog entry names and ids for`hyperledger-kubernetes-vp-cluster`, `hyperledger-kubernetes-membersrvc`, `hyperledger-kubernetes-cli`, `hyperledger-kubernetes-validating-peer` and `hyperledger-kubernetes-root-validating-peer` *only*

2017-02-28 17:24 UTC, grkvlt commented on catalog/hyperledger/kubernetes.bom
> +          - type: hyperledger-kubernetes-namespace
Bit keen; what other type of namespace would we have :frog:

2017-02-28 17:24 UTC, grkvlt commented on catalog/hyperledger/kubernetes.bom
> +          - type: hyperledger-kubernetes-membersrvc-pod
Ditto; only Kubernetes has Pods... Same for other Kubernetes specifics...

2017-03-01 03:36 UTC, mikezaccardo commented
@grkvlt I amended the commit to include name changes for only the entities you listed above.

2017-03-03 06:25 UTC, merged